#!/usr/bin/env bash

set -euxo pipefail

iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
trap 'rm -f "$iidfile"; docker rm -f "$cid" > /dev/null 2>&1 || true' EXIT

docker build --build-arg VNDR_VERSION=81cb8916aad3c8d06193f008dba3e16f82851f52 --iidfile "$iidfile" -f ./hack/dockerfiles/vendor.Dockerfile --force-rm .
iid=$(cat "$iidfile")
cid=$(docker create "$iid" noop)

rm -rf ./vendor
docker cp "$cid":/go/src/github.com/tonistiigi/buildkit-pack/vendor .
docker rm "$cid"
rm -f "$iidfile"