#!/usr/bin/env bash

set -euxo pipefail

iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
trap 'rm -f "$iidfile"' EXIT

docker build --build-arg VNDR_VERSION=81cb8916aad3c8d06193f008dba3e16f82851f52 --iidfile "$iidfile" -f ./hack/dockerfiles/vendor.Dockerfile --force-rm .
iid=$(cat "$iidfile")
diffs=$(docker run --rm "$iid" git status --porcelain -- vendor 2>/dev/null || true)
if [ -n "$diffs" ]; then
    {
        set +x
        echo 'The result of vndr differs'
        echo
        echo "$diffs"
        echo
        echo 'Please vendor your package with github.com/LK4D4/vndr.'
        echo
    } >&2
    exit 1
fi
echo 'Congratulations! All vendoring changes are done the right way.'
